version: 2

updates:
  # Enable version updates for Docker Compose
  - package-ecosystem: "docker-compose"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
